# Lua is not officially supported, but an erlang environment will do.
language: erlang

env:
  - LUA="lua5.1"
  - LUA="lua5.2"
  - LUA="luajit"

# Tool setup.
install:
  - sudo apt-get install libyaml-dev
  - sudo apt-get install luajit
  - sudo apt-get install libluajit-5.1-dev
  - sudo apt-get install lua5.1
  - sudo apt-get install liblua5.1-dev
  - sudo apt-get install lua5.2
  - sudo apt-get install liblua5.2-dev
  - sudo apt-get install luarocks

# Configure and build.
script:
  - ./bootstrap
  - ./configure LUA="$LUA"
  - make LUA="$LUA" LUA_INCDIR="/usr/include/$LUA" luarocks-config.lua
  - LUAROCKS_CONFIG=./luarocks-config.lua $LUA luarocks install stdlib
  - make rockspecs
  - LUAROCKS_CONFIG=./luarocks-config.lua $LUA luarocks make lyaml-git-1.rockspec

notifications:
  recipients:
    - gary@vaughan.pe
  email:
    on_success: change
    on_failure: always
