# Lua is not officially supported, but an erlang environment will do.
language: erlang

env:
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=luajit
  global:
    - LUAROCKS_CONFIG=luarocks-config.lua

# Tool setup.
install:
  - sudo apt-get install luajit
  - sudo apt-get install libluajit-5.1-dev
  - sudo apt-get install lua5.1
  - sudo apt-get install liblua5.1-dev
  - sudo apt-get install lua5.2
  - sudo apt-get install liblua5.2-dev
  - sudo apt-get install luarocks

# Configure and build.
script:
  - ./bootstrap
  - ./configure LUA="$LUA"
  - make LUA="$LUA" LUA_INCDIR="/usr/include/$LUA" luarocks-config.lua
  - $LUA `which luarocks` install stdlib
  - eval $($LUA `which luarocks` path); make rockspecs
  - $LUA `which luarocks` make lyaml-git-1.rockspec
